In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('flat_data_v2_4122019.csv')

c:\users\ilya kaftanov\appdata\local\programs\python\python37\lib\site-packages\IPython\core\interactiveshell.py:3044: DtypeWarning: Columns (0,5,11,12,13,14,22,25,30,38,42,44,46,55,56,57,59,62) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
data.head()

,allRoomsArea,balconiesCount,basicProfiScore,category,childrenAllowed,cianOnly,combinedWcsCount,creationDate,dealType,demolishedInMoscowProgramm,...,flatPriceDeposit,buildYear,buildMaterialType,buildfloorsCount,buildPassengerLiftsCount,buildCargoLiftsCount,userAccountType,userAgencyName,userAgentAvailabilityUserId,userPhoneNumber
0,0,0,1,flatRent,NaN,False,NaN,2019-04-10 13:06:55.413,rent,0.0,...,250000.0,NaN,NaN,85,0.0,0.0,agency,Rublevsky,6894696.0,79808888837
1,0,0,1,flatRent,NaN,False,NaN,2019-03-05 18:23:07.630,rent,0.0,...,200000.0,NaN,NaN,85,NaN,NaN,specialist,NaN,12895582.0,79684042188
2,0,0,1,flatRent,NaN,False,NaN,2018-08-09 18:23:51.497,rent,0.0,...,209000.0,NaN,NaN,85,4.0,4.0,agency,MOSCOW CITY LAB,7766192.0,79099004009
3,0,0,1,flatRent,NaN,False,NaN,2019-04-09 20:12:51.040,rent,0.0,...,230000.0,NaN,NaN,95,4.0,2.0,agency,MOSCOW CITY LAB,7766192.0,79099004009
4,0,0,1,flatRent,NaN,False,NaN,2019-02-25 14:42:49.043,rent,0.0,...,260000.0,NaN,NaN,87,NaN,NaN,agency,Rublevsky,6894696.0,79808888837

In [5]:
data['fullUrl'].shape

(8216,)

In [22]:
data[data['fullUrl'].duplicated()]['fullUrl']

68      https://www.cian.ru/rent/flat/201156001/
69      https://www.cian.ru/rent/flat/202327359/
70      https://www.cian.ru/rent/flat/202277885/
71      https://www.cian.ru/rent/flat/197798780/
72      https://www.cian.ru/rent/flat/202878778/
73      https://www.cian.ru/rent/flat/198009759/
74      https://www.cian.ru/rent/flat/201162958/
75      https://www.cian.ru/rent/flat/201022348/
76      https://www.cian.ru/rent/flat/202790081/
77      https://www.cian.ru/rent/flat/199233368/
78      https://www.cian.ru/rent/flat/199910010/
79      https://www.cian.ru/rent/flat/199172442/
80      https://www.cian.ru/rent/flat/201695646/
81      https://www.cian.ru/rent/flat/197958084/
82      https://www.cian.ru/rent/flat/202888671/
83      https://www.cian.ru/rent/flat/188519145/
84      https://www.cian.ru/rent/flat/193256004/
85      https://www.cian.ru/rent/flat/201067014/
86      https://www.cian.ru/rent/flat/201695646/
87      https://www.cian.ru/rent/flat/202888671/
88      https://www.cian.ru/rent/flat/202878778/
89      https://www.cian.ru/rent/flat/201156001/
90      https://www.cian.ru/rent/flat/202327359/
91      https://www.cian.ru/rent/flat/201067014/
92      https://www.cian.ru/rent/flat/197798780/
93      https://www.cian.ru/rent/flat/201162958/
94      https://www.cian.ru/rent/flat/193256004/
105     https://www.cian.ru/rent/flat/201695646/
106     https://www.cian.ru/rent/flat/202888671/
107     https://www.cian.ru/rent/flat/202878778/
                          ...
8186    https://www.cian.ru/rent/flat/201022348/
8187    https://www.cian.ru/rent/flat/202790081/
8188    https://www.cian.ru/rent/flat/199233368/
8189    https://www.cian.ru/rent/flat/199910010/
8190    https://www.cian.ru/rent/flat/199172442/
8191    https://www.cian.ru/rent/flat/201695646/
8192    https://www.cian.ru/rent/flat/197958084/
8193    https://www.cian.ru/rent/flat/202888671/
8194    https://www.cian.ru/rent/flat/188519145/
8195    https://www.cian.ru/rent/flat/193256004/
8196    https://www.cian.ru/rent/flat/201067014/
8197    https://www.cian.ru/rent/flat/201695646/
8198    https://www.cian.ru/rent/flat/202888671/
8199    https://www.cian.ru/rent/flat/202878778/
8200    https://www.cian.ru/rent/flat/201156001/
8201    https://www.cian.ru/rent/flat/202327359/
8202    https://www.cian.ru/rent/flat/201067014/
8203    https://www.cian.ru/rent/flat/197798780/
8204    https://www.cian.ru/rent/flat/201162958/
8205    https://www.cian.ru/rent/flat/193256004/
8206    https://www.cian.ru/rent/flat/169993274/
8207    https://www.cian.ru/rent/flat/155839668/
8208    https://www.cian.ru/rent/flat/173477738/
8209    https://www.cian.ru/rent/flat/202063534/
8210    https://www.cian.ru/rent/flat/196789750/
8211    https://www.cian.ru/rent/flat/197700500/
8212    https://www.cian.ru/rent/flat/189793851/
8213    https://www.cian.ru/rent/flat/174241022/
8214    https://www.cian.ru/rent/flat/194367634/
8215    https://www.cian.ru/rent/flat/181396431/
Name: fullUrl, Length: 6647, dtype: object

In [23]:
data[data['fullUrl'] == 'https://www.cian.ru/rent/flat/201156001/']

,allRoomsArea,balconiesCount,basicProfiScore,category,childrenAllowed,cianOnly,combinedWcsCount,creationDate,dealType,demolishedInMoscowProgramm,...,flatPriceDeposit,buildYear,buildMaterialType,buildfloorsCount,buildPassengerLiftsCount,buildCargoLiftsCount,userAccountType,userAgencyName,userAgentAvailabilityUserId,userPhoneNumber
50,0,0,1,flatRent,NaN,False,NaN,2019-02-08 13:09:09.580,rent,0.0,...,29000.0,1960.0,brick,8,1.0,NaN,specialist,NaN,2165162.0,79166551606
68,0,0,1,flatRent,NaN,False,NaN,2019-02-08 13:09:09.580,rent,0.0,...,29000.0,1960.0,brick,8,1.0,NaN,specialist,NaN,2165162.0,79166551606
89,0,0,1,flatRent,NaN,False,NaN,2019-02-08 13:09:09.580,rent,0.0,...,29000.0,1960.0,brick,8,1.0,NaN,specialist,NaN,2165162.0,79166551606
108,0,0,1,flatRent,NaN,False,NaN,2019-02-08 13:09:09.580,rent,0.0,...,29000.0,1960.0,brick,8,1.0,NaN,specialist,NaN,2165162.0,79166551606
199,0,0,1,flatRent,NaN,False,NaN,2019-02-08 13:09:09.580,rent,0.0,...,29000.0,1960.0,brick,8,1.0,NaN,specialist,NaN,2165162.0,79166551606
220,0,0,1,flatRent,NaN,False,NaN,2019-02-08 13:09:09.580,rent,0.0,...,29000.0,1960.0,brick,8,1.0,NaN,specialist,NaN,2165162.0,79166551606
311,0,0,1,flatRent,NaN,False,NaN,2019-02-08 13:09:09.580,rent,0.0,...,29000.0,1960.0,brick,8,1.0,NaN,specialist,NaN,2165162.0,79166551606
404,0,0,1,flatRent,NaN,False,NaN,2019-02-08 13:09:09.580,rent,0.0,...,29000.0,1960.0,brick,8,1.0,NaN,specialist,NaN,2165162.0,79166551606
422,0,0,1,flatRent,NaN,False,NaN,2019-02-08 13:09:09.580,rent,0.0,...,29000.0,1960.0,brick,8,1.0,NaN,specialist,NaN,2165162.0,79166551606
443,0,0,1,flatRent,NaN,False,NaN,2019-02-08 13:09:09.580,rent,0.0,...,29000.0,1960.0,brick,8,1.0,NaN,specialist,NaN,2165162.0,79166551606
459,0,0,1,flatRent,NaN,False,NaN,2019-02-08 13:09:09.580,rent,0.0,...,29000.0,1960.0,brick,8,1.0,NaN,specialist,NaN,2165162.0,79166551606
502,0,0,1,flatRent,NaN,False,NaN,2019-02-08 13:09:09.580,rent,0.0,...,29000.0,1960.0,brick,8,1.0,NaN,specialist,NaN,2165162.0,79166551606
573,0,0,1,flatRent,NaN,False,NaN,2019-02-08 13:09:09.580,rent,0.0,...,29000.0,1960.0,brick,8,1.0,NaN,NaN,NaN,NaN,70
617,0,0,1,flatRent,NaN,False,NaN,2019-02-08 13:09:09.580,rent,0.0,...,29000.0,1960.0,brick,8,1.0,NaN,specialist,NaN,2165162.0,79166551606
761,0,0,1,flatRent,NaN,False,NaN,2019-02-08 13:09:09.580,rent,0.0,...,29000.0,1960.0,brick,8,1.0,NaN,specialist,NaN,2165162.0,79166551606
805,18,0,1,flatRent,NaN,NaN,1.0,NaN,rent,0.0,...,29000.0,1960.0,brick,8,1.0,NaN,specialist,NaN,2165162.0,79166551606
821,0,0,1,flatRent,NaN,False,NaN,2019-02-08 13:09:09.580,rent,0.0,...,29000.0,1960.0,brick,8,1.0,NaN,specialist,NaN,2165162.0,79166551606
864,0,0,1,flatRent,NaN,False,NaN,2019-02-08 13:09:09.580,rent,0.0,...,29000.0,1960.0,brick,8,1.0,NaN,specialist,NaN,2165162.0,79166551606
882,0,0,1,flatRent,NaN,False,NaN,2019-02-08 13:09:09.580,rent,0.0,...,29000.0,1960.0,brick,8,1.0,NaN,specialist,NaN,2165162.0,79166551606
975,0,0,1,flatRent,NaN,False,NaN,2019-02-08 13:09:09.580,rent,0.0,...,29000.0,1960.0,brick,8,1.0,NaN,specialist,NaN,2165162.0,79166551606
996,0,0,1,flatRent,NaN,False,NaN,2019-02-08 13:09:09.580,rent,0.0,...,29000.0,1960.0,brick,8,1.0,NaN,specialist,NaN,2165162.0,79166551606
1040,0,0,1,flatRent,NaN,False,NaN,2019-02-08 13:09:09.580,rent,0.0,...,29000.0,1960.0,brick,8,1.0,NaN,specialist,NaN,2165162.0,79166551606
1109,0,0,1,flatRent,NaN,False,NaN,2019-02-08 13:09:09.580,rent,0.0,...,29000.0,1960.0,brick,8,1.0,NaN,specialist,NaN,2165162.0,79166551606
1125,0,0,1,flatRent,NaN,False,NaN,2019-02-08 13:09:09.580,rent,0.0,...,29000.0,1960.0,brick,8,1.0,NaN,specialist,NaN,2165162.0,79166551606
1143,0,0,1,flatRent,NaN,False,NaN,2019-02-08 13:09:09.580,rent,0.0,...,29000.0,1960.0,brick,8,1.0,NaN,specialist,NaN,2165162.0,79166551606
1164,0,0,1,flatRent,NaN,False,NaN,2019-02-08 13:09:09.580,rent,0.0,...,29000.0,1960.0,brick,8,1.0,NaN,specialist,NaN,2165162.0,79166551606
1233,0,0,1,flatRent,NaN,False,NaN,2019-02-08 13:09:09.580,rent,0.0,...,29000.0,1960.0,brick,8,1.0,NaN,specialist,NaN,2165162.0,79166551606
1277,0,0,1,flatRent,NaN,False,NaN,2019-02-08 13:09:09.580,rent,0.0,...,29000.0,1960.0,brick,8,1.0,NaN,specialist,NaN,2165162.0,79166551606
1343,18,0,1,flatRent,NaN,NaN,1.0,NaN,rent,0.0,...,29000.0,1960.0,brick,8,1.0,NaN,specialist,NaN,2165162.0,79166551606
1389,0,0,1,flatRent,NaN,False,NaN,2019-02-08 13:09:09.580,rent,0.0,...,29000.0,1960.0,brick,8,1.0,NaN,specialist,NaN,2165162.0,79166551606
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5985,0,0,1,flatRent,NaN,False,NaN,2019-02-08 13:09:09.580,rent,0.0,...,29000.0,1960.0,brick,8,1.0,NaN,specialist,NaN,2165162.0,79166551606
6003,0,0,1,flatRent,NaN,False,NaN,2019-02-08 13:09:09.580,rent,0.0,...,29000.0,1960.0,brick,8,1.0,NaN,specialist,NaN,2165162.0,79166551606
6021,0,0,1,flatRent,NaN,False,NaN,2019-02-08 13:09:09.580,rent,0.0,...,29000.0,1960.0,brick,8,1.0,NaN,specialist,NaN,2165162.0,79166551606
6089,0,0,1,flatRent,NaN,False,NaN,2019-02-08 13:09:09.580,rent,0.0,...,29000.0,1960.0,brick,8,1.0,NaN,specialist,NaN,2165162.0,79166551606
6210,0,0,1,flatRent,NaN,False,NaN,2019-02-08 13:09:09.580,rent,0.0,...,29000.0,1960.0,brick,8,1.0,NaN,specialist,NaN,2165162.0,79166551606
6251,0,0,1,flatRent,NaN,False,NaN,2019-02-08 13:09:09.580,rent,0.0,...,29000.0,1960.0,brick,8,1.0,NaN,specialist,NaN,2165162.0,79166551606
6269,0,0,1,flatRent,NaN,False,NaN,2019-02-08 13:09:09.580,rent,0.0,...,29000.0,1960.0,brick,8,1.0,NaN,specialist,NaN,2165162.0,79166551606
6390,0,0,1,flatRent,NaN,False,NaN,2019-02-08 13:09:09.580,rent,0.0,...,29000.0,1960.0,brick,8,1.0,NaN,specialist,NaN,2165162.0,79166551606
6531,0,0,1,flatRent,NaN,False,NaN,2019-02-08 13:09:09.580,rent,0.0,...,29000.0,1960.0,brick,8,1.0,NaN,specialist,NaN,2165162.0,79166551606
6574,0,0,1,flatRent,NaN,False,NaN,2019-02-08 13:09:09.580,rent,0.0,...,29000.0,1960.0,brick,8,1.0,NaN,specialist,NaN,2165162.0,79166551606
7320,0,0,1,flatRent,NaN,False,NaN,2019-02-08 13:09:09.580,rent,0.0,...,29000.0,1960.0,brick,8,1.0,NaN,specialist,NaN,2165162.0,79166551606
7339,0,0,1,flatRent,NaN,False,NaN,2019-02-08 13:09:09.580,rent,0.0,...,29000.0,1960.0,brick,8,1.0,NaN,specialist,NaN,2165162.0,79166551606
7405,0,0,1,flatRent,NaN,False,NaN,2019-02-08 13:09:09.580,rent,0.0,...,29000.0,1960.0,brick,8,1.0,NaN,specialist,NaN,2165162.0,79166551606
7451,0,0,1,flatRent,NaN,False,NaN,2019-02-08 13:09:09.580,rent,0.0,...,29000.0,1960.0,brick,8,1.0,NaN,specialist,NaN,2165162.0,79166551606
7467,0,0,1,flatRent,NaN,False,NaN,2019-02-08 13:09:09.580,rent,0.0,...,29000.0,1960.0,brick,8,1.0,NaN,specialist,NaN,2165162.0,79166551606
7485,0,0,1,flatRent,NaN,False,NaN,2019-02-08 13:09:09.580,rent,0.0,...,29000.0,1960.0,brick,8,1.0,NaN,specialist,NaN,2165162.0,79166551606
7578,0,0,1,flatRent,NaN,False,NaN,2019-02-08 13:09:09.580,rent,0.0,...,29000.0,1960.0,brick,8,1.0,NaN,specialist,NaN,2165162.0,79166551606
7624,0,0,1,flatRent,NaN,False,NaN,2019-02-08 13:09:09.580,rent,0.0,...,29000.0,1960.0,brick,8,1.0,NaN,specialist,NaN,2165162.0,79166551606
7643,0,0,1,flatRent,NaN,False,NaN,2019-02-08 13:09:09.580,rent,0.0,...,29000.0,1960.0,brick,8,1.0,NaN,specialist,NaN,2165162.0,79166551606
7662,0,0,1,flatRent,NaN,False,NaN,2019-02-08 13:09:09.580,rent,0.0,...,29000.0,1960.0,brick,8,1.0,NaN,specialist,NaN,2165162.0,79166551606
7681,0,0,1,flatRent,NaN,False,NaN,2019-02-08 13:09:09.580,rent,0.0,...,29000.0,1960.0,brick,8,1.0,NaN,specialist,NaN,2165162.0,79166551606
7750,0,0,1,flatRent,NaN,False,NaN,2019-02-08 13:09:09.580,rent,0.0,...,29000.0,1960.0,brick,8,1.0,NaN,specialist,NaN,2165162.0,79166551606
7844,0,0,1,flatRent,NaN,False,NaN,2019-02-08 13:09:09.580,rent,0.0,...,29000.0,1960.0,brick,8,1.0,NaN,specialist,NaN,2165162.0,79166551606
7860,0,0,1,flatRent,NaN,False,NaN,2019-02-08 13:09:09.580,rent,0.0,...,29000.0,1960.0,brick,8,1.0,NaN,specialist,NaN,2165162.0,79166551606
7956,0,0,1,flatRent,NaN,False,NaN,2019-02-08 13:09:09.580,rent,0.0,...,29000.0,1960.0,brick,8,1.0,NaN,specialist,NaN,2165162.0,79166551606
8000,0,0,1,flatRent,NaN,False,NaN,2019-02-08 13:09:09.580,rent,0.0,...,29000.0,1960.0,brick,8,1.0,NaN,specialist,NaN,2165162.0,79166551606
8019,0,0,1,flatRent,NaN,False,NaN,2019-02-08 13:09:09.580,rent,0.0,...,29000.0,1960.0,brick,8,1.0,NaN,specialist,NaN,2165162.0,79166551606
8163,0,0,1,flatRent,NaN,False,NaN,2019-02-08 13:09:09.580,rent,0.0,...,29000.0,1960.0,brick,8,1.0,NaN,specialist,NaN,2165162.0,79166551606
8179,0,0,1,flatRent,NaN,False,NaN,2019-02-08 13:09:09.580,rent,0.0,...,29000.0,1960.0,brick,8,1.0,NaN,specialist,NaN,2165162.0,79166551606
8200,0,0,1,flatRent,NaN,False,NaN,2019-02-08 13:09:09.580,rent,0.0,...,29000.0,1960.0,brick,8,1.0,NaN,specialist,NaN,2165162.0,79166551606